services:
  db-master:
    image: mysql:8.0
    container_name: db-master
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./db/master/my.cnf:/etc/mysql/conf.d/my.cnf:ro
      - ./db/master/init-master.sh:/docker-entrypoint-initdb.d/init-master.sh:ro
      - db-master-data:/var/lib/mysql
    networks:
      - db-net
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p$$MYSQL_ROOT_PASSWORD" ]
      interval: 5s
      timeout: 5s
      retries: 10

networks:
  web-net: { driver: bridge, ipam: { config: [ { subnet: 172.20.11.0/24 } ] } }
  was-net: { driver: bridge, ipam: { config: [ { subnet: 172.20.12.0/24 } ] } }
  db-net: { driver: bridge, ipam: { config: [ { subnet: 172.20.13.0/24 } ] } }

volumes:
  db-master-data:
